//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace rt.srz.ui.pvp.Controls.StatementSelectionWizardSteps {
    
    
    public partial class Step4 {
        
        /// <summary>
        /// Label10 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label Label10;
        
        /// <summary>
        /// Label1 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label Label1;
        
        /// <summary>
        /// documentUDL control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::rt.srz.ui.pvp.Controls.DocumentUdlUserControl documentUDL;
        
        /// <summary>
        /// Label16 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label Label16;
        
        /// <summary>
        /// lblLastName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lblLastName;
        
        /// <summary>
        /// tbLastName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.TextBox tbLastName;
        
        /// <summary>
        /// cvLastName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CustomValidator cvLastName;
        
        /// <summary>
        /// Label2 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label Label2;
        
        /// <summary>
        /// tbFirstName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.TextBox tbFirstName;
        
        /// <summary>
        /// hfFirstNameAutoCompleteID control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.HiddenField hfFirstNameAutoCompleteID;
        
        /// <summary>
        /// aceFirstNameIntellisense control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::AjaxControlToolkit.AutoCompleteExtender aceFirstNameIntellisense;
        
        /// <summary>
        /// cvFirstName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CustomValidator cvFirstName;
        
        /// <summary>
        /// Label3 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label Label3;
        
        /// <summary>
        /// tbMiddleName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.TextBox tbMiddleName;
        
        /// <summary>
        /// hfMiddleNameAutoCompleteID control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.HiddenField hfMiddleNameAutoCompleteID;
        
        /// <summary>
        /// aceMiddleNameIntellisense control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::AjaxControlToolkit.AutoCompleteExtender aceMiddleNameIntellisense;
        
        /// <summary>
        /// cvMiddleName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CustomValidator cvMiddleName;
        
        /// <summary>
        /// Label6 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label Label6;
        
        /// <summary>
        /// ddlRelationType control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        public global::System.Web.UI.WebControls.DropDownList ddlRelationType;
        
        /// <summary>
        /// cvRelationType control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CustomValidator cvRelationType;
        
        /// <summary>
        /// Label4 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label Label4;
        
        /// <summary>
        /// Label11 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label Label11;
        
        /// <summary>
        /// tbHomePhone control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        public global::System.Web.UI.WebControls.TextBox tbHomePhone;
        
        /// <summary>
        /// Label14 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label Label14;
        
        /// <summary>
        /// tbWorkPhone control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        public global::System.Web.UI.WebControls.TextBox tbWorkPhone;
        
        /// <summary>
        /// cvDocumentType control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CustomValidator cvDocumentType;
    }
}
