//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace rt.srz.ui.pvp.Controls.Administration {
    
    
    public partial class PdpsListDetailControl {
        
        /// <summary>
        /// UpdatePanel1 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        /// <summary>
        /// Label9 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label Label9;
        
        /// <summary>
        /// menuPanel control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.UpdatePanel menuPanel;
        
        /// <summary>
        /// menu1 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Menu menu1;
        
        /// <summary>
        /// contentUpdatePanel control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.UpdatePanel contentUpdatePanel;
        
        /// <summary>
        /// hfScrollPosition control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.HiddenField hfScrollPosition;
        
        /// <summary>
        /// scrollArea control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl scrollArea;
        
        /// <summary>
        /// pdpsGridView control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.GridView pdpsGridView;
        
        /// <summary>
        /// Panel1 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Panel Panel1;
        
        /// <summary>
        /// Image1 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Image Image1;
        
        /// <summary>
        /// lbText control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbText;
        
        /// <summary>
        /// Panel2 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Panel Panel2;
        
        /// <summary>
        /// pdpDetailControl control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::rt.srz.ui.pvp.Controls.Administration.PdpDetailWorkstationListControl pdpDetailControl;
        
        /// <summary>
        /// CollapsiblePanelExtender1 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::AjaxControlToolkit.CollapsiblePanelExtender CollapsiblePanelExtender1;
    }
}
