//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace rt.srz.ui.pvp.Controls.Administration {
    
    
    public partial class SearchByNameControl {
        
        /// <summary>
        /// UpdatePanel1 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        /// <summary>
        /// SearchPanel control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Panel SearchPanel;
        
        /// <summary>
        /// lbName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbName;
        
        /// <summary>
        /// tbName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.TextBox tbName;
        
        /// <summary>
        /// btnClear control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Button btnClear;
        
        /// <summary>
        /// btnSearch control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Button btnSearch;
    }
}
