//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rt.srz.business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rt.srz.business.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка применимости причины подачи заявления.
        /// </summary>
        public static string CaptionCheckCauseFilling {
            get {
                return ResourceManager.GetString("CaptionCheckCauseFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверки ФЛК аналогично ФЛК шлюза регионального сегмента.
        /// </summary>
        public static string CaptionCheckSrs {
            get {
                return ResourceManager.GetString("CaptionCheckSrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка соответствия даты рождения и даты смерти.
        /// </summary>
        public static string CaptionValidatorBirthAndDeathDate {
            get {
                return ResourceManager.GetString("CaptionValidatorBirthAndDeathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка соответствия даты рождения, даты выдачи документа УДЛ и даты заявления.
        /// </summary>
        public static string CaptionValidatorBirthAndIssueDate {
            get {
                return ResourceManager.GetString("CaptionValidatorBirthAndIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка даты рождения.
        /// </summary>
        public static string CaptionValidatorBirthdate {
            get {
                return ResourceManager.GetString("CaptionValidatorBirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения больше текущей даты.
        /// </summary>
        public static string CaptionValidatorBirthdateFuture {
            get {
                return ResourceManager.GetString("CaptionValidatorBirthdateFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка места рождения.
        /// </summary>
        public static string CaptionValidatorBirthplace {
            get {
                return ResourceManager.GetString("CaptionValidatorBirthplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка категории.
        /// </summary>
        public static string CaptionValidatorCategory {
            get {
                return ResourceManager.GetString("CaptionValidatorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка заполнения причины подачи заявления.
        /// </summary>
        public static string CaptionValidatorCauseFiling {
            get {
                return ResourceManager.GetString("CaptionValidatorCauseFiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка возраста для владения УДЛ.
        /// </summary>
        public static string CaptionValidatorChildrenAgeToHaveUdl {
            get {
                return ResourceManager.GetString("CaptionValidatorChildrenAgeToHaveUdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка запрета на работу для детей.
        /// </summary>
        public static string CaptionValidatorChildrenWork {
            get {
                return ResourceManager.GetString("CaptionValidatorChildrenWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка гражданства.
        /// </summary>
        public static string CaptionValidatorCitizenship {
            get {
                return ResourceManager.GetString("CaptionValidatorCitizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка прикрепленных файлов, в том числе фото и подписи.
        /// </summary>
        public static string CaptionValidatorContentFormat {
            get {
                return ResourceManager.GetString("CaptionValidatorContentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка даты выдачи ВС.
        /// </summary>
        public static string CaptionValidatorDateIssueTemporaryCertificate {
            get {
                return ResourceManager.GetString("CaptionValidatorDateIssueTemporaryCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка смерти.
        /// </summary>
        public static string CaptionValidatorDeath {
            get {
                return ResourceManager.GetString("CaptionValidatorDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка документа разрешающего проживание на территории РФ.
        /// </summary>
        public static string CaptionValidatorDocumentResidency {
            get {
                return ResourceManager.GetString("CaptionValidatorDocumentResidency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка документа УДЛ.
        /// </summary>
        public static string CaptionValidatorDocumentUdl {
            get {
                return ResourceManager.GetString("CaptionValidatorDocumentUdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка документ УДЛ у другого лица.
        /// </summary>
        public static string CaptionValidatorDocumentUdlExists {
            get {
                return ResourceManager.GetString("CaptionValidatorDocumentUdlExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка адреса электронной почты.
        /// </summary>
        public static string CaptionValidatorEmail {
            get {
                return ResourceManager.GetString("CaptionValidatorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка ЕНП.
        /// </summary>
        public static string CaptionValidatorEnp {
            get {
                return ResourceManager.GetString("CaptionValidatorEnp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка ЕНП  у другого лица.
        /// </summary>
        public static string CaptionValidatorEnpExists {
            get {
                return ResourceManager.GetString("CaptionValidatorEnpExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка соответствия имени и фамилии.
        /// </summary>
        public static string CaptionValidatorFirstAndLastName {
            get {
                return ResourceManager.GetString("CaptionValidatorFirstAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка имени.
        /// </summary>
        public static string CaptionValidatorFirstName {
            get {
                return ResourceManager.GetString("CaptionValidatorFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка пола.
        /// </summary>
        public static string CaptionValidatorGender {
            get {
                return ResourceManager.GetString("CaptionValidatorGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка соответствия имени полу.
        /// </summary>
        public static string CaptionValidatorGenderConformity {
            get {
                return ResourceManager.GetString("CaptionValidatorGenderConformity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка соответствия отчества полу.
        /// </summary>
        public static string CaptionValidatorGenderConformityMiddleName {
            get {
                return ResourceManager.GetString("CaptionValidatorGenderConformityMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка правил страхования.
        /// </summary>
        public static string CaptionValidatorInsuranceRules {
            get {
                return ResourceManager.GetString("CaptionValidatorInsuranceRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка соответствия даты рождения и даты подачи документа.
        /// </summary>
        public static string CaptionValidatorIssueDatePassportBirthCertificate {
            get {
                return ResourceManager.GetString("CaptionValidatorIssueDatePassportBirthCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка фамилии.
        /// </summary>
        public static string CaptionValidatorLastName {
            get {
                return ResourceManager.GetString("CaptionValidatorLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка отчества.
        /// </summary>
        public static string CaptionValidatorMiddleName {
            get {
                return ResourceManager.GetString("CaptionValidatorMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка вновь выданного ЕНП.
        /// </summary>
        public static string CaptionValidatorNewEnp {
            get {
                return ResourceManager.GetString("CaptionValidatorNewEnp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка типа полиса.
        /// </summary>
        public static string CaptionValidatorPolicyType {
            get {
                return ResourceManager.GetString("CaptionValidatorPolicyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка длины номера бланка полиса ОМС.
        /// </summary>
        public static string CaptionValidatorPolisCertificate {
            get {
                return ResourceManager.GetString("CaptionValidatorPolisCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка даты выдачи полиса.
        /// </summary>
        public static string CaptionValidatorPolisCertificateDateIssue {
            get {
                return ResourceManager.GetString("CaptionValidatorPolisCertificateDateIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка адреса регистрации.
        /// </summary>
        public static string CaptionValidatorRegistrationAddress {
            get {
                return ResourceManager.GetString("CaptionValidatorRegistrationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка документа регистрации.
        /// </summary>
        public static string CaptionValidatorRegistrationDocument {
            get {
                return ResourceManager.GetString("CaptionValidatorRegistrationDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка индекса адреса регистрации.
        /// </summary>
        public static string CaptionValidatorRegistrationPostcode {
            get {
                return ResourceManager.GetString("CaptionValidatorRegistrationPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка правил перестрахования.
        /// </summary>
        public static string CaptionValidatorReinsuranceRules {
            get {
                return ResourceManager.GetString("CaptionValidatorReinsuranceRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка документа УДЛ представителя.
        /// </summary>
        public static string CaptionValidatorRepresentativeDocumentUdl {
            get {
                return ResourceManager.GetString("CaptionValidatorRepresentativeDocumentUdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка имени и фамилии представителя.
        /// </summary>
        public static string CaptionValidatorRepresentativeFirstAndLastName {
            get {
                return ResourceManager.GetString("CaptionValidatorRepresentativeFirstAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка имени представителя.
        /// </summary>
        public static string CaptionValidatorRepresentativeFirstName {
            get {
                return ResourceManager.GetString("CaptionValidatorRepresentativeFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка фамилии представителя.
        /// </summary>
        public static string CaptionValidatorRepresentativeLastName {
            get {
                return ResourceManager.GetString("CaptionValidatorRepresentativeLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка отчества представителя.
        /// </summary>
        public static string CaptionValidatorRepresentativeMiddleName {
            get {
                return ResourceManager.GetString("CaptionValidatorRepresentativeMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка адреса проживания.
        /// </summary>
        public static string CaptionValidatorResidencyAddress {
            get {
                return ResourceManager.GetString("CaptionValidatorResidencyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка индекса адреса проживания.
        /// </summary>
        public static string CaptionValidatorResidencyPostcode {
            get {
                return ResourceManager.GetString("CaptionValidatorResidencyPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка СНИЛС.
        /// </summary>
        public static string CaptionValidatorSnils {
            get {
                return ResourceManager.GetString("CaptionValidatorSnils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка СНИЛС у другого человека.
        /// </summary>
        public static string CaptionValidatorSnilsExists {
            get {
                return ResourceManager.GetString("CaptionValidatorSnilsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка соответствия длины полей заявления.
        /// </summary>
        public static string CaptionValidatorStatementFieldLength {
            get {
                return ResourceManager.GetString("CaptionValidatorStatementFieldLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка номера ВС.
        /// </summary>
        public static string CaptionValidatorTemporaryCertificate {
            get {
                return ResourceManager.GetString("CaptionValidatorTemporaryCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка даты выдачи временного свидетельства.
        /// </summary>
        public static string CaptionValidatorTemporaryCertificateDateIssue {
            get {
                return ResourceManager.GetString("CaptionValidatorTemporaryCertificateDateIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка номер ВС в другом заявлении.
        /// </summary>
        public static string CaptionValidatorTemporaryCertificateNumberExists {
            get {
                return ResourceManager.GetString("CaptionValidatorTemporaryCertificateNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка попадания номера ВС в диапазон.
        /// </summary>
        public static string CaptionValidatorTemporaryCertificateNumberInRange {
            get {
                return ResourceManager.GetString("CaptionValidatorTemporaryCertificateNumberInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комплексная.
        /// </summary>
        public static string LevelCaption_Complex {
            get {
                return ResourceManager.GetString("LevelCaption_Complex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внешняя.
        /// </summary>
        public static string LevelCaption_External {
            get {
                return ResourceManager.GetString("LevelCaption_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простая.
        /// </summary>
        public static string LevelCaption_Simple {
            get {
                return ResourceManager.GetString("LevelCaption_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка заполненности отношения к застрахованному лицу.
        /// </summary>
        public static string ValidatorRelationTypeCaption {
            get {
                return ResourceManager.GetString("ValidatorRelationTypeCaption", resourceCulture);
            }
        }
    }
}
