//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace rt.srz.ui.pvp.Pages.Administrations {
    
    
    public partial class SmoDetailEx {
        
        /// <summary>
        /// smoDetailControl control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::rt.srz.ui.pvp.Controls.Administration.SmoDetailControl smoDetailControl;
        
        /// <summary>
        /// pdpsListDetailControl control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::rt.srz.ui.pvp.Controls.Administration.PdpsListDetailControl pdpsListDetailControl;
    }
}
