//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace rt.srz.ui.pvp.Controls {
    
    
    public partial class StatementSelectionWizardControl {
        
        /// <summary>
        /// hiddenTb control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.TextBox hiddenTb;
        
        /// <summary>
        /// hiddenBtn control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Button hiddenBtn;
        
        /// <summary>
        /// IsAvailableStep2 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.HiddenField IsAvailableStep2;
        
        /// <summary>
        /// IsAvailableStep3 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.HiddenField IsAvailableStep3;
        
        /// <summary>
        /// IsAvailableStep4 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.HiddenField IsAvailableStep4;
        
        /// <summary>
        /// IsAvailableStep5 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.HiddenField IsAvailableStep5;
        
        /// <summary>
        /// IsAvailableStep6 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.HiddenField IsAvailableStep6;
        
        /// <summary>
        /// cvErrors control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label cvErrors;
        
        /// <summary>
        /// confirm control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::rt.srz.ui.pvp.Controls.Common.ConfirmControl confirm;
        
        /// <summary>
        /// confirmPrint control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::rt.srz.ui.pvp.Controls.Common.ConfirmControl confirmPrint;
        
        /// <summary>
        /// confirmPrintVs control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::rt.srz.ui.pvp.Controls.Common.ConfirmControl confirmPrintVs;
        
        /// <summary>
        /// сonfirmPrintVsWithoutTemplate control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::rt.srz.ui.pvp.Controls.Common.ConfirmControl сonfirmPrintVsWithoutTemplate;
        
        /// <summary>
        /// confirmSave control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::rt.srz.ui.pvp.Controls.Common.ConfirmControl confirmSave;
        
        /// <summary>
        /// Wizard1 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Wizard Wizard1;
        
        /// <summary>
        /// WizardStep1 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.WizardStep WizardStep1;
        
        /// <summary>
        /// step1 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::rt.srz.ui.pvp.Controls.StatementSelectionWizardSteps.Step1 step1;
        
        /// <summary>
        /// WizardStep2 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.WizardStep WizardStep2;
        
        /// <summary>
        /// step2 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        public global::rt.srz.ui.pvp.Controls.StatementSelectionWizardSteps.Step2 step2;
        
        /// <summary>
        /// WizardStep3 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.WizardStep WizardStep3;
        
        /// <summary>
        /// step3 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::rt.srz.ui.pvp.Controls.StatementSelectionWizardSteps.Step3 step3;
        
        /// <summary>
        /// WizardStep4 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.WizardStep WizardStep4;
        
        /// <summary>
        /// step4 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::rt.srz.ui.pvp.Controls.StatementSelectionWizardSteps.Step4 step4;
        
        /// <summary>
        /// WizardStep5 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.WizardStep WizardStep5;
        
        /// <summary>
        /// step5 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::rt.srz.ui.pvp.Controls.StatementSelectionWizardSteps.Step5 step5;
        
        /// <summary>
        /// WizardStep6 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.WizardStep WizardStep6;
        
        /// <summary>
        /// step6 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::rt.srz.ui.pvp.Controls.StatementSelectionWizardSteps.Step6 step6;
    }
}
