USE [atl_srz_empty]
GO

/****** Object:  View [dbo].[PRZBUFT]    Script Date: 07/17/2014 15:23:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[PRZBUFT] WITH SCHEMABINDING
AS
SELECT     FAM, IM, OT, W, DOST, DR, DRA, DRT, MR, DS, SS, DOCTP, DOCS, DOCN, DOCDT, DOCORG, DOCEND, RDOCTP, RDOCS, RDOCN, RDOCDT, RDOCORG, RDOCEND, 
           BIRTH_OKSM, CN, SUBJ, RN, INDX, RNNAME, CITY, NP, UL, DOM, KOR, KV, DMJ, BOMJ, KATEG, PSUBJ, PRN, PINDX, PRNNAME, PCITY, PNP, PUL, PDOM, PKOR, 
           PKV, PDMJ, EMAIL, PHONE, ENP, Q, QOGRN, PRZ, OPDOC, SPOL, NPOL, OKATO, DHPOL, DBEG, DEND, DSTOP, DSTOP_CS, DVIZ, DZ, METH, POLISID, RSTOP, LPU, 
           LPUWK, LPUST, LPUUCH, LPUAUTO, LPUDT, LPUDX, SP, KT, OKVED, KLADRS, ERP, PETITION, FIOPR, CONTACT, ZFAM, ZIM, ZOT, ZT, ZDR, ZMR, ZDOCTP, ZDOCS, 
           ZDOCN, ZDOCDT, ZDOCORG, ZADDR, ZPHONE, PTYPE, NORD, DORD, OLDENP, KLADRG, KLADRP, ID, MID, DEDIT, ST, ET, AT, PID, PRZLOGID, OP, OLD_ENP, 
           OLDFAM, OLDIM, OLDOT, OLDDR, OLDW, OLDMR, OLDSS, OLDDOCTP, OLDDOCS, OLDDOCN, OLDDOCDT, OLDDOCORG, OLDDOCEND, OLDRDOCTP, OLDRDOCS, 
           OLDRDOCN, OLDRDOCDT, OLDRDOCORG, OLDRDOCEND, SFLK, EERP, EINS, REPL, NUM, OPID, OPSMO, OPPOL, POLPR, POLVID, RESCODE, RESULT, DEL, ZP1ID, 
           A08ID, VPDID, LOCK, FORCE
FROM   dbo.PRZBUF AS prz
WHERE  (SFLK IS NULL) AND 
       ((EERP IS NULL) OR (EERP IS NOT NULL AND NUM='-1')) AND
       ((EINS IS NULL) OR (EINS IS NOT NULL AND NUM='-1')) AND 
       ( (REPL = 'ОК!' OR REPL = 'полис нового образца включен в заявку на изготовление' OR REPL = 'Ок! Исправление только в СРЗ' OR REPL IS NULL) OR
         (EERP IS NOT NULL AND NUM='-1') OR
         (EINS IS NOT NULL AND NUM='-1')
       ) 
GO
