//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace rt.srz.ui.pvp.Controls.Twins {
    
    
    public partial class SearchKeyTypeDetailControl {
        
        /// <summary>
        /// lbTitle control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbTitle;
        
        /// <summary>
        /// lbKeyCode control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbKeyCode;
        
        /// <summary>
        /// tbKeyCode control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.TextBox tbKeyCode;
        
        /// <summary>
        /// rfKeyCode control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfKeyCode;
        
        /// <summary>
        /// lbKeyName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbKeyName;
        
        /// <summary>
        /// tbKeyName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.TextBox tbKeyName;
        
        /// <summary>
        /// rfKeyName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfKeyName;
        
        /// <summary>
        /// lbOperationKey control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbOperationKey;
        
        /// <summary>
        /// ddlOperationKey control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.DropDownList ddlOperationKey;
        
        /// <summary>
        /// Label1 control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label Label1;
        
        /// <summary>
        /// chbInsertion control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbInsertion;
        
        /// <summary>
        /// lbUseLastName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbUseLastName;
        
        /// <summary>
        /// chbUseLastName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbUseLastName;
        
        /// <summary>
        /// lbLastNameLength control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbLastNameLength;
        
        /// <summary>
        /// tbLastNameLength control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.TextBox tbLastNameLength;
        
        /// <summary>
        /// lbUseFirstName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbUseFirstName;
        
        /// <summary>
        /// chbUseFirstName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbUseFirstName;
        
        /// <summary>
        /// lbFirstNameLength control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbFirstNameLength;
        
        /// <summary>
        /// tbFirstNameLength control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.TextBox tbFirstNameLength;
        
        /// <summary>
        /// lbUseMiddleName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbUseMiddleName;
        
        /// <summary>
        /// chbUseMiddleName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbUseMiddleName;
        
        /// <summary>
        /// lbMiddleNameLength control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbMiddleNameLength;
        
        /// <summary>
        /// tbMiddleNameLength control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.TextBox tbMiddleNameLength;
        
        /// <summary>
        /// lbUseBirthDate control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbUseBirthDate;
        
        /// <summary>
        /// chbUseBirthDate control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbUseBirthDate;
        
        /// <summary>
        /// lbBirtdateLength control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbBirtdateLength;
        
        /// <summary>
        /// ddlBirtdateLength control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.DropDownList ddlBirtdateLength;
        
        /// <summary>
        /// lbUseBirthPlace control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbUseBirthPlace;
        
        /// <summary>
        /// chbUseBirthPlace control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbUseBirthPlace;
        
        /// <summary>
        /// lbUseSnils control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbUseSnils;
        
        /// <summary>
        /// chbUseSnils control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbUseSnils;
        
        /// <summary>
        /// lbUseUDLType control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbUseUDLType;
        
        /// <summary>
        /// chbUseUDLType control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbUseUDLType;
        
        /// <summary>
        /// lbUseUDLSeries control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbUseUDLSeries;
        
        /// <summary>
        /// chbUseUDLSeries control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbUseUDLSeries;
        
        /// <summary>
        /// lbUseUDLNumber control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbUseUDLNumber;
        
        /// <summary>
        /// chbUseUDLNumber control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbUseUDLNumber;
        
        /// <summary>
        /// lbUseOkato control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbUseOkato;
        
        /// <summary>
        /// chbUseOkato control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbUseOkato;
        
        /// <summary>
        /// lbUseRegistrationStreet control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbUseRegistrationStreet;
        
        /// <summary>
        /// chbUseRegistrationStreet control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbUseRegistrationStreet;
        
        /// <summary>
        /// lbRegistrationStreetLength control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbRegistrationStreetLength;
        
        /// <summary>
        /// tbRegistrationStreetLength control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.TextBox tbRegistrationStreetLength;
        
        /// <summary>
        /// lbUseRegistrationHouse control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbUseRegistrationHouse;
        
        /// <summary>
        /// chbUseRegistrationHouse control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbUseRegistrationHouse;
        
        /// <summary>
        /// lbUseRegistrationRoom control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbUseRegistrationRoom;
        
        /// <summary>
        /// chbUseRegistrationRoom control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbUseRegistrationRoom;
        
        /// <summary>
        /// lbUseResidenceStreet control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbUseResidenceStreet;
        
        /// <summary>
        /// chbUseResidenceStreet control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbUseResidenceStreet;
        
        /// <summary>
        /// lbResidenceStreetLength control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbResidenceStreetLength;
        
        /// <summary>
        /// tbResidenceStreetLength control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.TextBox tbResidenceStreetLength;
        
        /// <summary>
        /// lbUseResidenceHouse control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbUseResidenceHouse;
        
        /// <summary>
        /// chbUseResidenceHouse control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbUseResidenceHouse;
        
        /// <summary>
        /// lbUseResidenceRoom control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbUseResidenceRoom;
        
        /// <summary>
        /// chbUseResidenceRoom control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbUseResidenceRoom;
        
        /// <summary>
        /// lbDeleteTwinChar control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbDeleteTwinChar;
        
        /// <summary>
        /// chbDeleteTwinChar control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox chbDeleteTwinChar;
        
        /// <summary>
        /// lbTwinChars control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbTwinChars;
        
        /// <summary>
        /// tbTwinChars control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.TextBox tbTwinChars;
        
        /// <summary>
        /// btnSave control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Button btnSave;
        
        /// <summary>
        /// btnCancel control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Button btnCancel;
    }
}
