//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using NHibernate;
using rt.core.business.nhibernate;
using rt.core.model.core;

namespace rt.core.business.manager
{
    public partial interface IUserGroupManager : IManagerBase<rt.core.model.core.UserGroup, System.Guid>
    {
		// Get Methods
		IList<UserGroup> GetByGroupId(System.Guid group);
		IList<UserGroup> GetByUserId(System.Guid user);
    }

    partial class UserGroupManager : ManagerBase<rt.core.model.core.UserGroup, System.Guid>, IUserGroupManager
    {
        #region Get Methods

		
		public IList<UserGroup> GetByGroupId(System.Guid group)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(UserGroup));
			
			
			ICriteria groupCriteria = criteria.CreateCriteria("Group");
            groupCriteria.Add(NHibernate.Criterion.Expression.Eq("Id", group));
			
			return criteria.List<UserGroup>();
        }
		
		public IList<UserGroup> GetByUserId(System.Guid user)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(UserGroup));
			
			
			ICriteria userCriteria = criteria.CreateCriteria("User");
            userCriteria.Add(NHibernate.Criterion.Expression.Eq("Id", user));
			
			return criteria.List<UserGroup>();
        }
		
		#endregion
    }
}