//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using NHibernate;
using rt.core.business.nhibernate;
using rt.srz.model.srz;

namespace rt.srz.business.manager
{
    public partial interface IInsuredPersonManager : IManagerBase<rt.srz.model.srz.InsuredPerson, System.Guid>
    {
		// Get Methods
		IList<InsuredPerson> GetByDeadInfoId(System.Guid deadInfo);
		IList<InsuredPerson> GetByStatusId(System.Int32 concept);
    }

    partial class InsuredPersonManager : ManagerBase<rt.srz.model.srz.InsuredPerson, System.Guid>, IInsuredPersonManager
    {
        #region Get Methods

		
		public IList<InsuredPerson> GetByDeadInfoId(System.Guid deadInfo)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(InsuredPerson));
			
			
			ICriteria deadInfoCriteria = criteria.CreateCriteria("DeadInfo");
            deadInfoCriteria.Add(NHibernate.Criterion.Expression.Eq("Id", deadInfo));
			
			return criteria.List<InsuredPerson>();
        }
		
		public IList<InsuredPerson> GetByStatusId(System.Int32 concept)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(InsuredPerson));
			
			
			ICriteria conceptCriteria = criteria.CreateCriteria("Concept");
            conceptCriteria.Add(NHibernate.Criterion.Expression.Eq("Id", concept));
			
			return criteria.List<InsuredPerson>();
        }
		
		#endregion
    }
}