//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using NHibernate;
using rt.core.business.nhibernate;
using rt.srz.model.srz;

namespace rt.srz.business.manager
{
    public partial interface IRepresentativeManager : IManagerBase<rt.srz.model.srz.Representative, System.Guid>
    {
		// Get Methods
		IList<Representative> GetByDocumentId(System.Guid document);
		IList<Representative> GetByRelationTypeId(System.Int32 concept);
    
    }

    partial class RepresentativeManager : ManagerBase<rt.srz.model.srz.Representative, System.Guid>, IRepresentativeManager
    {
        #region Get Methods

		
		public IList<Representative> GetByDocumentId(System.Guid document)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(Representative));
			
			
			ICriteria documentCriteria = criteria.CreateCriteria("Document");
            documentCriteria.Add(NHibernate.Criterion.Expression.Eq("Id", document));
			
			return criteria.List<Representative>();
        }
		
		public IList<Representative> GetByRelationTypeId(System.Int32 concept)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(Representative));
			
			
			ICriteria conceptCriteria = criteria.CreateCriteria("Concept");
            conceptCriteria.Add(NHibernate.Criterion.Expression.Eq("Id", concept));
			
			return criteria.List<Representative>();
        }
		
		#endregion
    }
}