//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using NHibernate;
using rt.core.business.nhibernate;
using rt.srz.model.srz;

namespace rt.srz.business.manager
{
    public partial interface IRoleManager : IManagerBase<rt.srz.model.srz.Role, System.Guid>
    {
		// Get Methods
    }

    partial class RoleManager : ManagerBase<rt.srz.model.srz.Role, System.Guid>, IRoleManager
    {
        #region Get Methods

		
		#endregion
    }
}