//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using NHibernate;
using rt.core.business.nhibernate;
using rt.srz.model.srz;

namespace rt.srz.business.manager
{
    public partial interface IStatementChangeDateManager : IManagerBase<rt.srz.model.srz.StatementChangeDate, System.Guid>
    {
		// Get Methods
		IList<StatementChangeDate> GetByFieldId(System.Int32 concept);
		IList<StatementChangeDate> GetByStatementId(System.Guid statement);
		IList<StatementChangeDate> GetByVersion(System.Int32 version);
    
    }

    partial class StatementChangeDateManager : ManagerBase<rt.srz.model.srz.StatementChangeDate, System.Guid>, IStatementChangeDateManager
    {
        #region Get Methods

		
		public IList<StatementChangeDate> GetByFieldId(System.Int32 concept)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(StatementChangeDate));
			
			
			ICriteria conceptCriteria = criteria.CreateCriteria("Concept");
            conceptCriteria.Add(NHibernate.Criterion.Expression.Eq("Id", concept));
			
			return criteria.List<StatementChangeDate>();
        }
		
		public IList<StatementChangeDate> GetByStatementId(System.Guid statement)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(StatementChangeDate));
			
			
			ICriteria statementCriteria = criteria.CreateCriteria("Statement");
            statementCriteria.Add(NHibernate.Criterion.Expression.Eq("Id", statement));
			
			return criteria.List<StatementChangeDate>();
        }
		
		public IList<StatementChangeDate> GetByVersion(System.Int32 version)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(StatementChangeDate));
			
			
			criteria.Add(NHibernate.Criterion.Expression.Eq("Version", version));
			
			return criteria.List<StatementChangeDate>();
        }
		
		#endregion
    }
}