//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace rt.srz.ui.pvp.Controls.NSI {
    
    
    public partial class TemplateVsControl {
        
        /// <summary>
        /// lbTitle control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbTitle;
        
        /// <summary>
        /// lbName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbName;
        
        /// <summary>
        /// tbName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.TextBox tbName;
        
        /// <summary>
        /// positionsControl control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::rt.srz.ui.pvp.Controls.NSI.PositionsControl positionsControl;
        
        /// <summary>
        /// cbByDefault control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.CheckBox cbByDefault;
    }
}
