//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using NHibernate;
using rt.core.business.nhibernate;
using rt.fias.model.fias;

namespace rt.fias.business.manager
{
    public partial interface IHouseStateStatusManager : IManagerBase<rt.fias.model.fias.HouseStateStatus, int>
    {
		// Get Methods
    
    }

    partial class HouseStateStatusManager : ManagerBase<rt.fias.model.fias.HouseStateStatus, int>, IHouseStateStatusManager
    {
        #region Get Methods

		
		#endregion
    }
}