//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using NHibernate;
using rt.core.business.nhibernate;
using rt.atl.model.atl;

namespace rt.atl.business.manager
{
    public partial interface ISmoManager : IManagerBase<rt.atl.model.atl.Smo, int>
    {
		// Get Methods
		Smo GetByCODE(System.String code);
		IList<Smo> GetByDEDIT(System.DateTime dedit);
		IList<Smo> GetByPRID(System.Int32 prid);
    }

    partial class SmoManager : ManagerBase<rt.atl.model.atl.Smo, int>, ISmoManager
    {
        #region Get Methods

		
		public Smo GetByCODE(System.String code)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(Smo));
			
			
			criteria.Add(NHibernate.Criterion.Expression.Eq("Code", code));
			
			IList<Smo> result = criteria.List<Smo>();
			return (result.Count > 0) ? result[0] : null;
        }
		
		public IList<Smo> GetByDEDIT(System.DateTime dedit)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(Smo));
			
			
			criteria.Add(NHibernate.Criterion.Expression.Eq("Dedit", dedit));
			
			return criteria.List<Smo>();
        }
		
		public IList<Smo> GetByPRID(System.Int32 prid)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(Smo));
			
			
			criteria.Add(NHibernate.Criterion.Expression.Eq("Prid", prid));
			
			return criteria.List<Smo>();
        }
		
		#endregion
    }
}