//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using NHibernate;
using rt.core.business.nhibernate;
using rt.atl.model.atl;

namespace rt.atl.business.manager
{
    public partial interface ITestprocManager : IManagerBase<rt.atl.model.atl.Testproc, int>
    {
		// Get Methods
		Testproc GetByCODE(System.String code);
		IList<Testproc> GetByDEDIT(System.DateTime dedit);
    }

    partial class TestprocManager : ManagerBase<rt.atl.model.atl.Testproc, int>, ITestprocManager
    {
        #region Get Methods

		
		public Testproc GetByCODE(System.String code)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(Testproc));
			
			
			criteria.Add(NHibernate.Criterion.Expression.Eq("Code", code));
			
			IList<Testproc> result = criteria.List<Testproc>();
			return (result.Count > 0) ? result[0] : null;
        }
		
		public IList<Testproc> GetByDEDIT(System.DateTime dedit)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(Testproc));
			
			
			criteria.Add(NHibernate.Criterion.Expression.Eq("Dedit", dedit));
			
			return criteria.List<Testproc>();
        }
		
		#endregion
    }
}