//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using NHibernate;
using rt.core.business.nhibernate;
using rt.atl.model.atl;

namespace rt.atl.business.manager
{
    public partial interface IUecManager : IManagerBase<rt.atl.model.atl.Uec, int>
    {
		// Get Methods
		IList<Uec> GetByPID(System.Int32 person);
		IList<Uec> GetByPOLIS(System.Int32 poli);
		IList<Uec> GetByUECLASTSTATUS(System.Int32 uechiststatus);
		IList<Uec> GetByUFILE(System.Int32 ufile);
		Uec GetByNCARD(System.String ncard);
    
    }

    partial class UecManager : ManagerBase<rt.atl.model.atl.Uec, int>, IUecManager
    {
        #region Get Methods

		
		public IList<Uec> GetByPID(System.Int32 person)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(Uec));
			
			
			ICriteria personCriteria = criteria.CreateCriteria("Person");
            personCriteria.Add(NHibernate.Criterion.Expression.Eq("Id", person));
			
			return criteria.List<Uec>();
        }
		
		public IList<Uec> GetByPOLIS(System.Int32 poli)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(Uec));
			
			
			ICriteria poliCriteria = criteria.CreateCriteria("Poli");
            poliCriteria.Add(NHibernate.Criterion.Expression.Eq("Id", poli));
			
			return criteria.List<Uec>();
        }
		
		public IList<Uec> GetByUECLASTSTATUS(System.Int32 uechiststatus)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(Uec));
			
			
			ICriteria uechiststatusCriteria = criteria.CreateCriteria("Uechiststatus");
            uechiststatusCriteria.Add(NHibernate.Criterion.Expression.Eq("Id", uechiststatus));
			
			return criteria.List<Uec>();
        }
		
		public IList<Uec> GetByUFILE(System.Int32 ufile)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(Uec));
			
			
			ICriteria ufileCriteria = criteria.CreateCriteria("Ufile");
            ufileCriteria.Add(NHibernate.Criterion.Expression.Eq("Id", ufile));
			
			return criteria.List<Uec>();
        }
		
		public Uec GetByNCARD(System.String ncard)
        {
            ICriteria criteria = Session.GetISession().CreateCriteria(typeof(Uec));
			
			
			criteria.Add(NHibernate.Criterion.Expression.Eq("Ncard", ncard));
			
			IList<Uec> result = criteria.List<Uec>();
			return (result.Count > 0) ? result[0] : null;
        }
		
		#endregion
    }
}