//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using NHibernate;
using rt.core.business.nhibernate;
using rt.atl.model.atl;

namespace rt.atl.business.manager
{
    public partial interface IVsendManager : IManagerBase<rt.atl.model.atl.Vsend, int>
    {
		// Get Methods
    
    }

    partial class VsendManager : ManagerBase<rt.atl.model.atl.Vsend, int>, IVsendManager
    {
        #region Get Methods

		
		#endregion
    }
}