//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace rt.srz.ui.pvp.Pages {
    
    
    public partial class SMCWrite {
        
        /// <summary>
        /// ScriptManager control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::AjaxControlToolkit.ToolkitScriptManager ScriptManager;
        
        /// <summary>
        /// hfLastName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.HiddenField hfLastName;
        
        /// <summary>
        /// hfFirstName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.HiddenField hfFirstName;
        
        /// <summary>
        /// hfMiddleName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.HiddenField hfMiddleName;
        
        /// <summary>
        /// hfBirthdate control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.HiddenField hfBirthdate;
        
        /// <summary>
        /// hfOGRN control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.HiddenField hfOGRN;
        
        /// <summary>
        /// hfOKATO control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.HiddenField hfOKATO;
        
        /// <summary>
        /// hfDateFrom control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.HiddenField hfDateFrom;
        
        /// <summary>
        /// hfDateTo control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.HiddenField hfDateTo;
        
        /// <summary>
        /// lbLastName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbLastName;
        
        /// <summary>
        /// lbFirstName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbFirstName;
        
        /// <summary>
        /// lbMiddleName control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbMiddleName;
        
        /// <summary>
        /// lbBirthdate control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbBirthdate;
        
        /// <summary>
        /// lbOGRN control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbOGRN;
        
        /// <summary>
        /// lbOKATO control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbOKATO;
        
        /// <summary>
        /// lbDateFrom control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbDateFrom;
        
        /// <summary>
        /// lbDateTo control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbDateTo;
        
        /// <summary>
        /// mpeSecutiryModulePinCode control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::AjaxControlToolkit.ModalPopupExtender mpeSecutiryModulePinCode;
        
        /// <summary>
        /// btnFake control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Button btnFake;
        
        /// <summary>
        /// pnSecutiryModulePinCode control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Panel pnSecutiryModulePinCode;
        
        /// <summary>
        /// lbSecutiryModulePinCode control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbSecutiryModulePinCode;
        
        /// <summary>
        /// tbSecutiryModulePinCode control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.TextBox tbSecutiryModulePinCode;
        
        /// <summary>
        /// btnSecutiryModuleConfirmPin control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Button btnSecutiryModuleConfirmPin;
        
        /// <summary>
        /// btnSecutiryModuleCancelPin control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Button btnSecutiryModuleCancelPin;
        
        /// <summary>
        /// mpePinCode control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::AjaxControlToolkit.ModalPopupExtender mpePinCode;
        
        /// <summary>
        /// pnPinCode control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Panel pnPinCode;
        
        /// <summary>
        /// lbPinCode control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lbPinCode;
        
        /// <summary>
        /// tbPinCode control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.TextBox tbPinCode;
        
        /// <summary>
        /// btnConfirmPin control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Button btnConfirmPin;
        
        /// <summary>
        /// btnCancelPin control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Button btnCancelPin;
        
        /// <summary>
        /// lblQuestion control.
        /// </summary>
        
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        
        protected global::System.Web.UI.WebControls.Label lblQuestion;
    }
}
